server:
  port: 8088
spring:
  application:
    name: mybatis-plus-example-server
  pid:
    file: ${spring.application.name}.pid
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_game?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      auto-commit: true
logging:
  level:
    me.gaopq.demo.mbp.example: debug
  file:
    name: ${spring.application.name}.log